# secrets.toml




DEEPSEEK_API_KEY = "4a8e6e227750fba44f0713c1f4c7831548950b0ba3d12533cf670864f6c3901e"
ScrapeGraphAI_KEY = "sgai-f313f2c7-73e2-41e8-adcf-9061e01eca53"
GROQ_API_KEY = "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"
API_KEY = "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"
# Password
PASSWORD = "AICCORE2025"